### ISSUE TITLE
passwordcallback.hpp:10:1: error: expected class-name before '{' token

### ISSUE THREAD

**Issue by hirowhite** [Open-Transactions/Moneychanger#106]
Log below.
Linux Mint
Linux h-desktop 3.8.0-25-generic #37-Ubuntu SMP Thu Jun 6 20:47:30 UTC 2013 i686 athlon i686 GNU/Linux

compiling ../../src/core/applicationmc.cpp
In file included from ../../src/core/applicationmc.cpp:7:0:
../../src/core/passwordcallback.hpp:10:1: error: expected class-name before '{' token
../../src/core/applicationmc.cpp:25:55: error: 'OTCallback' has not been declared
../../src/core/applicationmc.cpp: In function 'bool SetupPasswordCallback(OTCaller&, int&)':
../../src/core/applicationmc.cpp:27:19: error: invalid use of incomplete type 'class OTCaller'
In file included from ../../src/core/applicationmc.cpp:14:0:
/usr/local/include/opentxs/OTAsymmetricKey.hpp:142:7: error: forward declaration of 'class OTCaller'
../../src/core/applicationmc.cpp: In member function 'void MTApplicationMC::appStarting()':
../../src/core/applicationmc.cpp:81:31: error: aggregate 'OTCaller passwordCaller' has incomplete type and cannot be defined
make[2]: *** [debug/applicationmc.o] Error 1
make[2]: Leaving directory `/home/x/work/ot/Moneychanger/build-moneychanger-Desktop_Qt_5_1_1_GCC_32bit-Debug/moneychanger-qt'
make[1]: Leaving directory `/home/x/work/ot/Moneychanger/build-moneychanger-Desktop_Qt_5_1_1_GCC_32bit-Debug/moneychanger-qt'
make[1]: *** [debug] Error 2
make: *** [sub-moneychanger-qt-make_first-ordered] Error 2
04:51:00: The process "/usr/bin/make" exited with code 2.
Error while building/deploying project moneychanger (kit: Desktop Qt 5.1.1 GCC 32bit)
When executing step 'Make'
04:51:00: Elapsed time: 00:17.

**Comment by yamamushi** [comment]
@hirowhite are you still having trouble with this issue?
