### ISSUE TITLE
Segmentation fault when creating nym

### ISSUE THREAD

**Issue by justusranvier** [Open-Transactions/Moneychanger#118]
When creating a new nym from a fresh install state (~/.ot does not exist), Moneychanger crashes immediately after entering the master password:

<code>
<pre>
Welcome to Open Transactions -- version 0.94.0-482-g851da7a
Adding DB 
"File Handler File does not Exist." 
"/var/lib/justus/.ot//mc_db" 
Database opened 
Creating Tables 
"Database /mc_db created." 
Lanugage Setting wasn't set in the database. Inserting system default:  "en_US" 
Could not update language to:  "en_US.qm" 
OTCaller::setCallback: Attempting to set the password OTCallback pointer...
OTCaller::setCallback: FYI, the password OTCallback pointer was set.
OTLookupCaller::setCallback: Attempting to set the OTNameLookup pointer...
OTLookupCaller::setCallback: FYI, the OTNameLookup pointer was set.
LoadWallet: Wallet file does not exist: wallet.xml. Creating...
Loading pending name registrations: 
Namecoin update timer called. 
No operations necessary that need an unlocked wallet. 
Setting up Nym table 
Default Nym wasn't set in the database. Inserting blank record... 
Default Server wasn't set in the database. Inserting blank record... 
Default Asset Type wasn't set in the database. Inserting blank record... 
Default Account wasn't set in the database. Inserting blank record... 
Database Populated 
"" 
"" 
QMetaObject::connectSlotsByName: No matching signal for on_refreshButton_clicked()
Overview Opened 
QMetaObject::connectSlotsByName: No matching signal for on_viewContactButton_clicked(bool)
QMetaObject::connectSlotsByName: No matching signal for on_addContactButton_clicked(bool)
QMetaObject::connectSlotsByName: No matching signal for on_existingContactButton_clicked(bool)
QMetaObject::connectSlotsByName: No matching signal for on_deleteButton_clicked(bool)
QMetaObject::connectSlotsByName: No matching signal for on_acceptButton_clicked(bool)
QMetaObject::connectSlotsByName: No matching signal for on_cancelButton_clicked(bool)
QMetaObject::connectSlotsByName: No matching signal for on_discardOutgoingButton_clicked(bool)
QMetaObject::connectSlotsByName: No matching signal for on_discardIncomingButton_clicked(bool)
QMetaObject::connectSlotsByName: No matching signal for on_msgButton_clicked(bool)
================ Populate: Looping through the accounts in the wallet...
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
QMetaObject::connectSlotsByName: No matching signal for on_btnAddressAdd_clicked()
QMetaObject::connectSlotsByName: No matching signal for on_btnAddressDelete_clicked()
....++++++
.......................++++++
OTCaller::callTwo: FYI, Executing password callback (two)...
QMetaObject::connectSlotsByName: No matching signal for on_MTDlgPasswordConfirm_accepted()
OTCaller::GetPassword: FYI, returning password after invoking a (probably Java) password dialog.
souped_up_pass_cb: 0 length password was returned from the API password callback. Substituting default password 'test'.
BuildFolderPath: Made new folder: /var/lib/justus/.ot/client_data/certs/
BuildFolderPath: Made new folder: /var/lib/justus/.ot/client_data/nyms/
......++++++
......++++++
.........++++++
..++++++
BuildFolderPath: Made new folder: /var/lib/justus/.ot/client_data/credentials/
BuildFolderPath: Made new folder: /var/lib/justus/.ot/client_data/credentials/otx8eED7ts6YKeR3ti9dr6XRwUWYZuvy5izx/
....++++++
...............++++++
....++++++
...................++++++
.............................................................................................++++++
..............................................................++++++
"" 
"" 
MTDetailEdit Iteration:  0 
"MTDetailEdit::RefreshRecords: Name: Justus, ID: otx8eED7ts6YKeR3ti9dr6XRwUWYZuvy5izx" 
"SETTING current row to 0 on the tableWidget." 
SETTING current row to  0  on the tableWidget. 
"NYM ID: otx8eED7ts6YKeR3ti9dr6XRwUWYZuvy5izx" 
Segmentation fault
</pre>
</code>

**Comment by yamamushi** [comment]
Can you post the exact steps necessary to reproduce this?

**Comment by justusranvier** [comment]
1. Compile opentxs and moneychanger
2. Start moneychanger for the first time, with no existing ~/.ot directory
3. Click "Identities"
4. "Add"
5. Enter a name, then "Next"
6. Leave keysize at the default value and "Next" again
7. Leave the type as Self-Signed, and "Commit"
8. Leave alternate location blank and "Finish"
9. Enter a passphrase twice and click "Ok"

Segfault

**Comment by yamamushi** [comment]
4ea7b864710e13f2136308753201ccda772cd72d should have resolved this, please let me know.

**Comment by justusranvier** [comment]
Yes, that fixes the problem for me.

**Comment by yamamushi** [comment]
Awesome!
