### ISSUE TITLE
mcrpcservice.cpp

### ISSUE THREAD

**Issue by ychaim** [Open-Transactions/Moneychanger#139]
Hi There,

Thank you very much for updating the repo ..

Can i ask you about this ../../src/rpc/mcrpcservice.cpp  ?

/usr/include/qt5/QtCore/qjsonobject.h:57:5: note:   candidate expects 0 arguments, 1 provided
make[2]: *** [release/mcrpcservice.o] Error 1
make[2]: Leaving directory `/root/Moneychanger/project/moneychanger-qt'
make[1]: *** [release] Error 2
make[1]: Leaving directory `/root/Moneychanger/project/moneychanger-qt'
make: *** [sub-moneychanger-qt-make_first-ordered] Error 2

I got error and i can't compiler it ..

Regards,

ytz

**Comment by yamamushi** [comment]
Hello,

Are you still seeing this error with the latest code?
