### ISSUE TITLE
compile moneychanger.cpp:1308:45: error: ‘class opentxs::OT_ME’ has no member named ‘create_nym’

### ISSUE THREAD

**Issue by drgorb** [Open-Transactions/Moneychanger#150]
on Ubuntu 15.10 I could `make install` opentxs but then I get this error when running `make` on MoneyChanger:

    moneychanger.cpp:1308:45: error: ‘class opentxs::OT_ME’ has no member named ‘create_nym’

**Comment by yamamushi** [comment]
Was this using the Develop or Master branch?

**Comment by drgorb** [comment]
master

**Comment by yamamushi** [comment]
Please try using the develop branch, as the master branch is out of sync with the develop branch of opentxs :)

**Comment by drgorb** [comment]
now the make complains that `qjsonrpc/qjsonrpc.pro` is not available. I checked the repo and the folder is empty in projects and missing in src.

**Comment by justusranvier** [comment]
qjsonrpc is a git submodule.

You need to run "git submodule init" and "git submodule update" in the top level directory to make sure it's present.

**Comment by drgorb** [comment]
thank you for the hint. the jsonrpc submodule was updated, but compilation still stops with an error

    XmlRPC.h:12:31: fatal error: xmlrpc-c/girerr.hpp: No such file or directory

**Comment by yamamushi** [comment]
Do you happen to have the xmlrpc-c library installed?

On OSX you can install it with $brew installs xmlrpc-c

**Comment by drgorb** [comment]
one step further. Yay!! On ubuntu the package is called `libxmlrpc-c++8-dev` 

The build still fails though:

    agreementdetails.hpp:143:15: error: field ‘m_dateTimeValidFrom’ has incomplete type ‘QDateTime’

**Comment by justusranvier** [comment]
That error is caused by using qmake version 4 instead of qmake version 5.

Moneychanger only works with Qt5

**Comment by drgorb** [comment]
once this is successful I shall write a guide for Ubuntu. In the mean time, I still get an error:

    /gui/widgets/nymdetails.cpp:645:39: error: ‘class opentxs::OT_ME’ has no member named ‘create_nym_ecdsa’

output of `qmake --version`

    QMake version 3.0
    Using Qt version 5.4.2 in /usr/lib/x86_64-linux-gnu

qt packages installed:

    libqwt-qt5-6 
    libqwt-qt5-dev
    libqwtmathml-qt5-6
    libqwtmathml-qt5-dev 
    qt5-default:amd64
    qt5-qmake:amd64 
    qtbase5-dev:amd64 
    qtbase5-dev-tools 
    qtchooser 
    qttranslations5-l10n

**Comment by justusranvier** [comment]
"no member named ‘create_nym_ecdsa’" is caused by the version of opentxs you have installed being too old.

You need the most recent version of the develop branch.

**Comment by drgorb** [comment]
Hooray!! It went through and the app launched
