### ISSUE TITLE
Moneychanger issues on Linux Mint 16 based on Ubuntu 13.10

### ISSUE THREAD

**Issue by Tectract** [Open-Transactions/Moneychanger#83]
I can compile without error, but when I cd into the project/moneychanger directory and run:
./moneychanger-qt (with the otserver running in another window)

I get a "transaction history" window that seems functional, but the main moneychanger window is defunct, doesn't respond to "close window" event, and shows whatever was on the screen behind the window when it opened, rather than the moneychanger gui.

this is on Linux Mint 13.10

**Comment by yamamushi** [comment]
@Tectract are you still seeing this issue?
